/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NewsletterNewsletterIdImport } from './routes/newsletter/$newsletterId'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const NewsletterNewsletterIdRoute = NewsletterNewsletterIdImport.update({
  path: '/newsletter/$newsletterId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/newsletter/$newsletterId': {
      id: '/newsletter/$newsletterId'
      path: '/newsletter/$newsletterId'
      fullPath: '/newsletter/$newsletterId'
      preLoaderRoute: typeof NewsletterNewsletterIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  NewsletterNewsletterIdRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/newsletter/$newsletterId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/newsletter/$newsletterId": {
      "filePath": "newsletter/$newsletterId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
